#!/usr/bin/env bash
# copies a file to the remote server
if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
	exit 1;
fi
scp -i "$4" -o StrictHostKeyChecking=yes "$1" "$3"@"$2":'~/'"$1"
