#!/usr/bin/env bash
sudo apt-get install nginx -y
cd /etc/nginx/
mv nginx.conf nginx.conf.backup
echo "events { } http { server { listen 80; return 200 "Hello World!\n"; } }" > nginx.conf
nginx -s reload
