#!/usr/bin/env bash
# installs nginx and configures it
sudo apt-get install nginx -y
cd /etc/nginx/ || exit
mv nginx.conf nginx.conf.backup
echo -e "$(printf 'events { } http { server { listen 80; return 200 "Hello World!\n"; } }')" > nginx.conf
nginx -s reload
