#!/usr/bin/env bash
# "To infinity and beyond", and handles INT, QUIT and TERM signals
EXITTING () {
	rm /var/run/myscript.pid;
	exit;
}
HATEIT () {
	echo 'I hate the kill command';
	EXITTING;
}
LOVEME () {
	echo 'Y U no love me?!';
}
trap EXITTING QUIT
trap HATEIT TERM
trap LOVEME INT
echo $$ > /var/run/myscript.pid
while true; do
	echo "To infinity and beyond"
	sleep 2
done
