#!/usr/bin/env bash
# this searchs for a process called '4-to_infinity_and_beyond' to kill it
#shellcheck disable=SC2009
if (( $(ps -U root -u root x | grep 4-to_infinity_and_beyond) -ne '' ))
then
kill "$(ps -U root -u root x | grep 4-to_infinity_and_beyond | tr ' ' ':' | awk -F: '{ print $2 }' | head -n 1)"
fi
