#!/usr/bin/env bash
# prints "To infinity and beyond" indefinitly and traps termination signals
INVINCIBILITY () {
	echo "I am invincible!!!";
}
trap INVINCIBILITY SIGTERM
while true; do
	echo "To infinity and beyond";
	sleep 2
done
