#!/usr/bin/env bash
# same but says checks for the luck status too
i=1
while [ $i -le 10 ]
do
	if [ $i = 4 ]; then
		echo "bad luck"
	elif [ $i = 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i+=1))
done
