#!/usr/bin/env bash
# attempts to forward traffic from 8080 to 80
sudo ufw disable
sudo sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw
sudo echo '
*nat
:POSTROUTING ACCEPT [0:0]

# Forward traffic from port 8080 to port 80.
-A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination 52.87.232.14:80
-A POSTROUTING -s 192.168.1.0/24 -j MASQUERADE

COMMIT' >> /etc/ufw/before.rules
sudo ufw enable
