#!/usr/bin/env bash
# switch to nginx user and run its server
sudo service apache2 stop
sudo chmod 777 /etc/nginx/nginx.conf
sudo sed -i -e 's/ 80 / 8080 /' -e 's/:80 /:8080 /' /etc/nginx/sites-enabled/default
sudo -u nginx nginx
